# Generated by Django 4.1.3 on 2022-11-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shoppify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Area', models.CharField(max_length=50)),
                ('About_user', models.TextField()),
                ('Birthday', models.DateField()),
            ],
        ),
    ]
