# Generated by Django 4.1.3 on 2022-11-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0003_rename_birthday_student_data_dath_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='Fathername',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='Email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='Password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='Username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
