# Generated by Django 4.1.3 on 2022-11-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0004_student_data_fathername_alter_student_data_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_data',
            old_name='Fathername',
            new_name='Father_name',
        ),
    ]
