# Generated by Django 4.1.3 on 2022-11-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0007_adeemaform_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adeemaform_1',
            old_name='name',
            new_name='User_name',
        ),
    ]
