# Generated by Django 4.1.3 on 2022-11-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0008_rename_name_adeemaform_1_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adeemaform_1',
            new_name='adeemaform',
        ),
    ]
