# Generated by Django 4.1.3 on 2022-11-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0009_rename_adeemaform_1_adeemaform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adeemaform',
            old_name='User_name',
            new_name='Your_name',
        ),
    ]
