# Generated by Django 4.1.3 on 2022-11-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0010_rename_user_name_adeemaform_your_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adeemaform',
            old_name='Your_name',
            new_name='name',
        ),
    ]
