# Generated by Django 4.1.3 on 2022-11-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0011_rename_your_name_adeemaform_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adeemaform',
            new_name='adeemaform_1',
        ),
    ]
