# Generated by Django 4.1.3 on 2022-11-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0013_alter_adeemaform_1_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adeemaform_1',
            new_name='adeemaform',
        ),
    ]
