# Generated by Django 4.1.3 on 2022-11-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0014_rename_adeemaform_1_adeemaform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adeemaform',
            new_name='adeemaform_1',
        ),
    ]
