# Generated by Django 4.1.3 on 2022-11-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0015_rename_adeemaform_adeemaform_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeemaform_1',
            name='datetime',
            field=models.CharField(default='', max_length=50),
        ),
    ]
