# Generated by Django 4.1.3 on 2022-11-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0017_alter_adeemaform_1_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeemaform_1',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
