# Generated by Django 4.1.3 on 2022-11-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0020_alter_adeemaform_1_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_data',
            name='Dath_Of_Birth',
        ),
        migrations.AddField(
            model_name='student_data',
            name='datetime',
            field=models.DateTimeField(default=''),
        ),
    ]
