# Generated by Django 4.1.3 on 2022-11-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0021_remove_student_data_dath_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_data',
            old_name='datetime',
            new_name='Dath_Of_Birth',
        ),
    ]
