# Generated by Django 4.1.3 on 2022-11-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0025_alter_student_data_dath_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adeemaform_1',
            name='datetime',
        ),
    ]
