# Generated by Django 4.1.3 on 2022-11-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0027_adeemaform_1_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adeemaform_1',
        ),
    ]
