# Generated by Django 4.1.3 on 2022-11-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmart', '0029_adeemaform_1_remove_student_data_dath_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adeemaform_1',
        ),
    ]
